[project]
channels = ["conda-forge"]
name = "min-max-rl"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"

[pypi-dependencies]
min-max-rl = { path = ".", editable = true }
