[project]
channels = ["conda-forge"]
name = "min-max-rl"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12,<3.13"

[pypi-dependencies]
min-max-rl = { path = ".", editable = true }
numpy = ">=2.2.6, <3"
torch = ">=2.7.0, <3"
tensorboard = ">=2.19.0, <3"
jax = { version = ">=0.4.21, <0.6", extras = ["cuda12"] }
chex = ">=0.1.86, <0.2"
flax = ">=0.8.4, <0.11"
gymnax = ">=0.0.9, <0.0.10"
mlflow = ">=2.22.0, <3"
brax = ">=0.12.3, <0.13"
